// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginSystem.djinni

#pragma once

#include "crypto.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeCrypto final : ::djinni::JniInterface<::crypto::Crypto, NativeCrypto> {
public:
    using CppType = std::shared_ptr<::crypto::Crypto>;
    using CppOptType = std::shared_ptr<::crypto::Crypto>;
    using JniType = jobject;

    using Boxed = NativeCrypto;

    ~NativeCrypto();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeCrypto>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeCrypto>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeCrypto();
    friend ::djinni::JniClass<NativeCrypto>;
    friend ::djinni::JniInterface<::crypto::Crypto, NativeCrypto>;

};

}  // namespace djinni_generated
