cc_library(
  name = "bson-c",
  srcs = ["lib/libbson-static-1.0.a"],
  hdrs = glob(["include/libbson-1.0/*.h"]),
  visibility = ["//visibility:public"],
)


cc_library(
  name = "mongoc-c",
  srcs = ["lib/libmongoc-static-1.0.a"],
  hdrs = glob(["include/libmongoc-1.0/*.h"]),
  visibility = ["//visibility:public"],
)