load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cc_proto_library")

cc_proto_library(
  name = "login_system_proto",
  protos = ["login_system.proto"],
  with_grpc = True,
  visibility = ["//visibility:public"],
)