source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

install! 'cocoapods', :deterministic_uuids => false

target 'login_client_ios' do
  # Depend on the generated RouteGuide library.
  pod 'login_client_ios', :path => '.'
end
