// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginSystem.djinni

#import <Foundation/Foundation.h>
@class LSSCrypto;


@interface LSSCrypto : NSObject

+ (nullable LSSCrypto *)create;

- (nonnull NSString *)getHelloWorld;

@end
