// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginSystem.djinni

#include "crypto.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LSSCrypto;

namespace djinni_generated {

class Crypto
{
public:
    using CppType = std::shared_ptr<::crypto::Crypto>;
    using CppOptType = std::shared_ptr<::crypto::Crypto>;
    using ObjcType = LSSCrypto*;

    using Boxed = Crypto;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

