// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginSystem.djinni

#import "LSSCrypto+Private.h"
#import "LSSCrypto.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface LSSCrypto ()

- (id)initWithCpp:(const std::shared_ptr<::crypto::Crypto>&)cppRef;

@end

@implementation LSSCrypto {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::crypto::Crypto>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::crypto::Crypto>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable LSSCrypto *)create {
    try {
        auto objcpp_result_ = ::crypto::Crypto::create();
        return ::djinni_generated::Crypto::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)getHelloWorld {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->get_hello_world();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto Crypto::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto Crypto::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<LSSCrypto>(cpp);
}

}  // namespace djinni_generated

@end
