// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loginSystem.djinni

#pragma once

#include <memory>
#include <string>

namespace crypto {

class Crypto {
public:
    virtual ~Crypto() {}

    static std::shared_ptr<Crypto> create();

    virtual std::string get_hello_world() = 0;
};

}  // namespace crypto
